echo updating ...
sudo apt-get update && apt-get upgrade -y

echo installing pigpio ...
sudo apt-get install -y pigpio 

echo enabling pigpio ...
sudo systemctl enable pigpiod

echo starting pigpio ...
sudo systemctl start pigpiod

echo installing pip3 ...
sudo apt-get install -y python3-pip

echo installing other python dependencies using pip ...
pip3 install -r requirements.txt